services:
  postgres:
    image: postgres:17
    container_name: dpf_postgres
    environment:
      POSTGRES_DB: dpf_wallet_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - dpf_postgres_data:/var/lib/postgresql/data

volumes:
  dpf_postgres_data:
