# APPLICATION
# ===============================
spring.application.name=dpf-wallet-service
server.port=8083

# POSTGRESQL DATABASE
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/dpf_wallet_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

## KAFKA (basic safe defaults)
## ===============================
#spring.kafka.bootstrap-servers=localhost:9092
#
## REDIS
## ===============================
#spring.data.redis.host=localhost
#spring.data.redis.port=6379

# ACTUATOR
# ===============================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always